force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Registro centralizado de endereços utilizados no sistema para referência e associação com outros objetos.</description>
    <label>Localização</label>
    <nameField>
        <label>Nome da Localização</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localizações</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o endereço foi validado ou confirmado.</description>
    <inlineHelpText>Marque esta opção caso o endereço tenha sido verificado e esteja correto.</inlineHelpText>
    <label>Verificado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ViaCepService.cls
public class ViaCepService {
    
    @future(callout=true)
    public static void verifyLocationCep(Id locationId, String cep) {
        
        String cleanCep = cep.replaceAll('[^0-9]', '');
        
        if (cleanCep.length() != 8) {
            System.debug('CEP inválido: ' + cep);
            return;
        }

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://viacep.com.br/ws/' + cleanCep + '/json/');
        request.setMethod('GET');
        request.setTimeout(10000);

        try {
            HttpResponse response = http.send(request);

            if (response.getStatusCode() == 200) {
                
                Map<String, Object> jsonResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                
                Location__c locToUpdate = new Location__c(Id = locationId);
                
                if (jsonResponse.containsKey('erro')) {
                    locToUpdate.Verified__c = false;
                    System.debug('ViaCEP retornou erro para o CEP: ' + cep);
                } else {
                    locToUpdate.Verified__c = true;
                }
                
                update locToUpdate;
                
            } else {
                System.debug('Erro na chamada da API ViaCEP. Status: ' + response.getStatusCode());
            }
            
        } catch (Exception e) {
            System.debug('Exceção fatal ao tentar verificar o CEP: ' + e.getMessage());
        }
    }
}