force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Registro centralizado de endereços utilizados no sistema para referência e associação com outros objetos.</description>
    <label>Localização</label>
    <nameField>
        <label>Nome da Localização</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localizações</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Cidade do endereço.</description>
    <inlineHelpText>Insira o nome da cidade conforme padrão oficial.</inlineHelpText>
    <label>Cidade</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Código postal do endereço (CEP).</description>
    <inlineHelpText>Insira o CEP no formato correto do país (ex: 00000-000 para Brasil).</inlineHelpText>
    <label>Código Postal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Estado ou província do endereço.</description>
    <inlineHelpText>Informe o estado utilizando nome completo ou sigla padronizada (ex: PE, SP, RJ).</inlineHelpText>
    <label>Estado</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Logradouro do endereço (rua, avenida, etc.).</description>
    <inlineHelpText>Informe o nome da rua/avenida e, se aplicável, número e complemento.</inlineHelpText>
    <label>Rua</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o endereço foi validado ou confirmado.</description>
    <inlineHelpText>Marque esta opção caso o endereço tenha sido verificado e esteja correto.</inlineHelpText>
    <label>Verificado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ViaCepAddressService.cls
public class ViaCepAddressService {

    public class ViaCepResponse {
        public String logradouro;
        public String localidade;
        public String uf;
        public Boolean erro;
    }

    public static void validateAddress(Id locationId) {

        Location__c loc = [
            SELECT Id, Street__c, City__c, State__c, Postal_Code__c, Verified__c
            FROM Location__c
            WHERE Id = :locationId
            LIMIT 1
        ];

        String cep = loc.Postal_Code__c.replaceAll('[^0-9]', '');

        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:ViaCEP/ws/' + cep + '/json/');
        req.setMethod('GET');

        Http http = new Http();
        HttpResponse res = http.send(req);

        if (res.getStatusCode() == 200) {

            ViaCepResponse data =
                (ViaCepResponse) JSON.deserialize(res.getBody(), ViaCepResponse.class);

            if (data.erro == true) {
                loc.Verified__c = false;
            } else {

                if (data.localidade == loc.City__c &&
                    data.uf == loc.State__c) {

                    loc.Verified__c = true;

                } else {
                    loc.Verified__c = false;
                }
            }
        }

        update loc;
    }
}