force-app/main/default/objects/Medical_Event__c/Medical_Event__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por gerenciar eventos médicos, incluindo detalhes operacionais, participantes e logística.</description>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>N° do Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Médicos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Event__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>Data e hora de término do evento.</description>
    <inlineHelpText>Informe quando o evento será finalizado.</inlineHelpText>
    <label>Data/Hora de Término</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o evento está ativo no momento.</description>
    <inlineHelpText>Marque se o evento estiver ocorrendo atualmente.</inlineHelpText>
    <label>Ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteOldEventsBatch.cls
global class DeleteOldEventsBatch implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {

        return Database.getQueryLocator([
            SELECT Id
            FROM Medical_Event__c
            WHERE End_Date_Time__c <= :System.now().addMonths(-2)
            AND Live__c = false
        ]);
    }
   
    global void execute(Database.BatchableContext bc, List<Medical_Event__c> scope) {

        try {
            EventBatchHandler.deleteOldEvents(scope);

        } catch (Exception e) {
            System.debug('Erro ao deletar eventos: ' + e.getMessage());
        }
    }

    global void finish(Database.BatchableContext bc) {

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[] {'sfdcpanther@gmail.com'});
        mail.setSubject('Batch Completed');
        mail.setPlainTextBody('The batch job to delete old events has completed successfully.');

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}